[mysql]
host = "106.75.119.141"
port = "3306"
db = "devsecops"
username = "root"
password = "Qihoo2020"

[redis]
host = "106.75.119.141"
port = "6379"
password = "Qihoo2020"

[kafka]
broker = ["117.50.109.103:9092"]

[docker]
host = "unix:///var/run/docker.sock"
version = "1.25"

[scancenter]
analyzer_url = "http://127.0.0.1:12001/api/images/analyzer/"
anchore_url = "http://127.0.0.1:12001/api/images/anchore/"

[anchore]
anchore_url = "http://117.50.109.103:8228"
username = "admin"
password = "foobar"
