[mysql]
host = "106.75.119.141"
port = "3306"
db = "devsecops"
username = "root"
password = "Qihoo2020"

[redis]
host = "106.75.119.141"
port = "6379"
password = "Qihoo2020"

[kafka]
broker = ["117.50.109.103:9092"]

[anchore]
host = "117.50.109.103"
port = "8228"
username = "admin"
password = "foobar"
