[mysql]
host = "106.75.119.141"
port = "3306"
db = "devsecops"
username = "root"
password = "Qihoo2020"

[redis]
host = "106.75.119.141"
port = "6379"
password = "Qihoo2020"

[kafka]
broker = ["117.50.109.103:9092"]

[docker]
host = "http://10.16.29.51:2375"
version = "v1.40"

[scancenter]
analyzer_url = "http://10.16.29.51:12001/api/images/analyzer/"
anchore_url = "http://10.16.29.51:12001/api/images/anchore/"
trivy_url = "http://10.16.29.51:12001/api/images/trivy/"

[anchore]
anchore_url = "http://10.16.29.51:8228"
username = "admin"
password = "foobar"

[trivy]
host_url = "http://10.16.29.51:2375"
version = "v1.40"


