[mysql]
host = "106.75.119.141"
port = "3306"
db = "devsecops"
username = "root"
password = "Qihoo2020"

[redis]
host = "106.75.119.141"
port = "6379"
password = "Qihoo2020"

[kafka]
broker = ["117.50.109.103:9092"]

[docker]
docker_url = "http://127.0.0.1:2375"
version = "v1.40"

[scancenter]
analyzer_url = "http://117.50.109.103:12001/api/images/analyzer/"
anchore_url = "http://117.50.109.103:12001/api/images/anchore/"
trivy_url = "http://117.50.109.103:12001/api/images/trivy/"
clair_url = "http://117.50.109.103:12001/api/images/clair/"

[anchore]
anchore_url = "http://127.0.0.1:8228"
username = "admin"
password = "foobar"

[trivy]
trivy_url = "http://127.0.0.1:2375"
version = "v1.40"
image = "docker.io/aquasec/trivy:latest"
container_name = "trivy_container"
volume_name = "trivy_vol"
target_path = "/root/.cache/"
file_name = "result.json"
container_cmd = ["-f", "json", "-o"]

[clair]
clair_url = "http://127.0.0.1:2375"
version = "v1.40"
clair_addr = "CLAIR_ADDR=127.0.0.1"
image = "uhub.service.ucloud.cn/devsecops/klar:latest"
container_name = "klar_container"
