version: '3'

services:
  heimdall-analyzer:
    image: uhub.service.ucloud.cn/devsecops/heimdall:208ac5b
    network_mode: "host"
    command: -type analyzer
    restart: always
    volumes:
      - ../../configs/pro.toml:/app/configs/pro.toml

  heimdall-anchore:
    image: uhub.service.ucloud.cn/devsecops/heimdall:208ac5b
    network_mode: "host"
    command: -type scanner-anchore
    restart: always
    volumes:
      - ../../configs/pro.toml:/app/configs/pro.toml

  heimdall-trivy:
    image: uhub.service.ucloud.cn/devsecops/heimdall:208ac5b
    network_mode: "host"
    command: -type scanner-trivy
    restart: always
    volumes:
      - ../../configs/pro.toml:/app/configs/pro.toml

  heimdall-clair:
    image: uhub.service.ucloud.cn/devsecops/heimdall:208ac5b
    network_mode: "host"
    command: -type scanner-clair
    restart: always
    volumes:
      - ../../configs/pro.toml:/app/configs/pro.toml